//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF354_MiniProj_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rental
    {
        public int rental_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> car_id { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
    
        public virtual car car { get; set; }
        public virtual customer customer { get; set; }
    }
}
